name: Docker Image Build Workflow
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        tag:
          - ros_kinetic
          - ros_kinetic_cuda9.2_chainer
          - ros_melodic
          - ros_melodic_realsense
          - ros_melodic_cuda10.0
          - ros_melodic_cuda9.2_chainer
          - ros_noetic
          - ros_noetic_realsense
          - ros_noetic_cuda11.3_tensorRT7.2
          - ros_noetic_cuda11.3_torch1.10
    name: build_${{ matrix.tag }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.tag }}
          push: false
          tags: sktometometo/ubuntu-ros:${{ matrix.tag }}
