name: Docker Image Build Workflow
on:
  push:
    branches:
      - 'master'
jobs:
  build_ros_kinetic_cuda92_chainer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Images
        run: docker build -t sktometometo/ubuntu-ros:ros_kinetic_cuda9.2_chainer ./ros_kinetic_cuda9.2_chainer
  build_ros_melodic_cuda92_chainer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Images
        run: docker build -t sktometometo/ubuntu-ros:ros_melodic_cuda9.2_chainer ./ros_melodic_cuda9.2_chainer
  build_ros_melodic_cuda100:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Images
        run: docker build -t sktometometo/ubuntu-ros:ros_melodic_cuda10.0 ./ros_melodic_cuda10.0
  build_ros_melodic_realsense:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Images
        run: docker build -t sktometometo/ubuntu-ros:ros_melodic_realsense ./ros_melodic_realsense
  build_ros_noetic_cuda113_torch110:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Images
        run: docker build -t sktometometo/ubuntu-ros:ros_noetic_cuda11.3_torch1.10 ./ros_noetic_cuda11.3_torch1.10
