name: Docker Image Push Workflow

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  push_docker_image:
    name: push_${{ matrix.image }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        image:
          - ros_kinetic
          - ros_kinetic_cuda9.2_chainer
          - ros_melodic
          - ros_melodic_realsense
          - ros_melodic_cuda10.0
          - ros_melodic_cuda9.2_chainer
          - ros_noetic
          - ros_noetic_realsense
          - ros_noetic_cuda11.3_tensorrt7.2
          - ros_noetic_cuda11.3_torch1.11
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.image }}
          push: true
          tags: sktometometo/${{ matrix.image }}:${{ github.ref_name }}
